const menuBtn=document.querySelector('.menu-btn');const nav=document.querySelector('.nav');menuBtn?.addEventListener('click',()=>nav.classList.toggle('open'));document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));document.getElementById('year').textContent=new Date().getFullYear();
let facultyData=[];
async function loadFaculty(){const grid=document.getElementById('facultyGrid');try{const r=await fetch('/api/faculty');if(!r.ok)throw new Error('Could not load faculty');const d=await r.json();facultyData=d.faculty||[];document.getElementById('facultyCount').textContent=facultyData.length;grid.innerHTML=facultyData.map((f,i)=>{const photo=f.photo?`<img src="${escapeHtml(f.photo)}" alt="${escapeHtml(f.name)}">`:escapeHtml(f.initials||getInitials(f.name));return `<article class="faculty-card ${i===0?'featured':''}" onclick="openProfile('${escapeHtml(f.id)}')"><div class="avatar">${photo}</div><div><span class="role">${escapeHtml(f.role||'FACULTY')}</span><h3>${escapeHtml(f.name)}</h3>${f.designation?`<p>${escapeHtml(f.designation)}</p>`:''}<div class="hint">Click to view profile →</div></div></article>`}).join('');}catch(e){grid.innerHTML='<div class="loading">Faculty profiles are temporarily unavailable.</div>';}}
function getInitials(n){return n.replace(/^Dr\.\s*/i,'').split(/\s+/).slice(0,3).map(x=>x[0]).join('').toUpperCase();}
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function openProfile(id){const f=facultyData.find(x=>x.id===id);if(!f)return;const photo=f.photo?`<img class="profile-photo" src="${escapeHtml(f.photo)}" alt="${escapeHtml(f.name)}">`:`<div class="profile-placeholder">${escapeHtml(f.initials||getInitials(f.name))}</div>`;document.getElementById('profileContent').innerHTML=`<div class="profile-head">${photo}<div><span class="profile-label">${escapeHtml(f.role||'FACULTY')}</span><h2>${escapeHtml(f.name)}</h2>${f.designation?`<p>${escapeHtml(f.designation)}</p>`:''}</div></div>${f.qualification?`<div class="profile-section"><h4>Qualification</h4><p>${escapeHtml(f.qualification)}</p></div>`:''}${f.about?`<div class="profile-section"><h4>About</h4><p>${escapeHtml(f.about)}</p></div>`:''}${f.research?`<div class="profile-section"><h4>Research Interests</h4><p>${escapeHtml(f.research)}</p></div>`:''}${f.email?`<div class="profile-section"><h4>Email</h4><p>${escapeHtml(f.email)}</p></div>`:''}<button class="edit-profile-btn" onclick="startEdit('${escapeHtml(f.id)}')">Edit Profile</button>`;const m=document.getElementById('profileModal');m.classList.add('show');m.setAttribute('aria-hidden','false');}
function closeProfile(){const m=document.getElementById('profileModal');m.classList.remove('show');m.setAttribute('aria-hidden','true');}
document.getElementById('profileModal').addEventListener('click',e=>{if(e.target.id==='profileModal')closeProfile();});
async function startEdit(id){sessionStorage.setItem('editFacultyId',id);const r=await fetch('/admin.html');if(r.ok)location.href='/admin.html';}
loadFaculty();